name: build docs w/ compilation

on: [push, pull_request]

jobs:
  Matrix-build:
    runs-on: macos-latest
    # container: node:latest 

    # See: https://github.com/marketplace/actions/setup-miniconda#important
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: fix pip
        run: python -m ensurepip --upgrade
      - uses: conda-incubator/setup-miniconda@v3
        with:
          # mamba-version: "*"
          # channels: conda-forge
          # use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          # auto-update-conda: true
          # conda-remove-defaults: true
          activate-environment: teqpflshdocs
          environment-file: doc/environment.yml
      - name: install teqpflsh, built from source
        # https://github.com/usnistgov/ChebTools/blob/master/README.md#prerequisites regarding the need for libgcc
        # conda install libgcc libstdcxx-ng
        run: |
          conda list
          python -m pip install .
          cd doc 
          make html
      - name: archive docs 
        run: cd doc && python -c "import shutil; shutil.make_archive('teqpflshdocs', 'xztar', 'build')"
      - uses: actions/upload-artifact@v4
        with:
          path: |
            ./doc/*.tar.xz
